server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

keycloak:
  client:
    id: sicdiapp
    secret: vO80rEC4luarQQ2DVMZyehKte9lUUc1k
    realm: sso-sicie
    auth-server-url: http://10.23.228.150:7780/
    grant-type: password
    grant-type-app: client_credentials
    users-path: /users
menu:
  client:
    base: http://srvmenu.aks-dev.internal
    prefix: /v1/
    service: /menu/informacion
    userInfo: /usuario/informacion

user:
  client:
    base: http://srvusuario.aks-dev.internal
    prefix: /v1/Usuario
    service: /guardarUsuarioPersona
    searchbyid: /consultaId
    updatepassword: /contrasena/
    resetPassword: /reestablecerContrasena
    searchByEmail: /consultaCorreo
    employeeDependencyRol: /FuncionarioDependenciaRol/

spring:
  datasource:
    url: jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = 10.23.228.150)(PORT = 1521))(CONNECT_DATA =(SERVER = DEDICATED)(SERVICE_NAME = RSISDOC)))
    username: DOC
    password: "***Sicdi2026+-*"
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    connection-timeout: 20000
    idle-timeout: 300000
    max-lifetime: 1200000
    minimum-idle: 20
    maximum-pool-size: 100
    auto-commit: true
    read-only: true
    pool-name: SICDI-HikariPool
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      initialization-fail-timeout: 10000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: DOC
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.Oracle12cDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://10.23.228.150:7780/realms/sso-sicie
